services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend

    container_name: cover-letter-backend
    environment:
      - PORT=8080 # Internal container port
    networks:
      - cover-letter-network
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      target: dev # Development stage
    container_name: cover-letter-frontend

    volumes:
      - "./frontend:/app" # Mount frontend
      - "/app/node_modules" # Ignore node_modules

    ports:
      - 3000:3000
    networks:
      - cover-letter-network

networks:
  cover-letter-network:
    driver: bridge
