# ------ Dependencies stage ------
FROM oven/bun:1.2.18-alpine@sha256:a7df687a2f684ee2f7404e2592039e192d75d26a04f843e60d9fc342741187d0 AS deps
WORKDIR /app

# Install dependencies
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# ------ Development stage ------
FROM deps AS dev

# Run
CMD ["bun", "run", "dev"]

