name: Deploy to Server

on:
  push:
    branches:
      - main # or 'master', or your preferred branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest # The runner environment for this job

    steps:
      - name: Setup ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            cd ~/cover-letter
            git pull 
            sudo docker compose down
            sudo docker compose up -d --build
