name: Deploy to Server

on:
  push:
    branches:
      - main # or 'master', or your preferred branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest # The runner environment for this job

    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cover-letter
            GIT_SSH_COMMAND='ssh -i ~/.ssh/github' git pull
            sudo docker compose down
            sudo docker compose up -d --build
